declare global {
    interface Window {
        state: any;
        keyHandlers: any;
        interactionMap: any;
        modeHandlers: any;
        MDMath: any;
        db: any;
        history: any;
        renderCanvas: () => void;
        clearAllCaches: () => void;
        getShapeCache: (id: string) => any;
        getShapeRenderBounds: (id: string) => any;
        markShapeDirty: (id: string) => void;
        drawShapeToCanvasContext: (ctx: any, shapeId: string) => void;
        rasterizeInactiveLayers: () => void;
        renderMinimap: () => void;
        renderGuides: (id: string, container: any) => void;
        pushHistory: () => void;
        undo: () => void;
        redo: () => void;
        handleInputUpdate: (e: any) => void;
        handleInputUpdate_old: (event: string, detail?: any, rawEvent?: any) => void;
        updateTransformPivotToCenter: () => void;
        initDB: () => void;
        initOffscreenCanvases: () => void;
        resizeOffscreenCanvases: () => void;
        saveDrawing: () => Promise<void>;
        loadGallery: () => void;
        switchView: (viewId: string) => void;
        addLayer: () => void;
        deleteLayer: (id: string) => void;
        renderLayerList: () => void;
        startNewDrawing: (type?: string) => void;
        importImageFile: () => void;
        getDom: (pat: string) => any;
        getDoms: (pat: string) => any[];
        getDomsOf: (root: any, pat: string) => any[];
        newElm: (tag: string) => any;
        getMainCanvasSVGVector: () => any;
        getMainCanvasSVGPoint: () => any;
        getModifierState: (e: any) => string;
        isFocusEditable: () => boolean;
        toggleHelpModal: () => void;
        handleQuitToGallery: (ctx: any) => void;
        handleOpenSearch: (ctx: any) => void;
        handleOpenCommand: (ctx: any) => void;
        handleSearchNext: (ctx: any) => void;
        handleSearchPrev: (ctx: any) => void;
        handleFocusVertexPrev: (ctx: any) => void;
        handleFocusVertexNext: (ctx: any) => void;
        performSearch: (val: string) => void;
        applySearchResult: () => void;
        closeSearchMode: (commit: boolean) => void;
        closeCommandMode: (commit: boolean) => void;
        switchSettingsTab: (tab: string) => void;
        initWebGLPatternRenderer: () => void;
        renderPatternWebGL: (positions: any, name: string) => any;
        generateCoonsPatchMesh: (shape: any) => any;
        generateStrokeCoonsPatchMesh: (shape: any) => any;
        currentRenderCoonsCount: number;
        resetRenderCoonsCount: () => void;
        addShapeAt: (type: string, x: number, y: number) => void;
        createWrap: () => void;
        resolveBezierDependencies: () => void;
    }

    const state: any;
    const keyHandlers: any;
    const interactionMap: any;
    const modeHandlers: any;
    const MDMath: any;
    const db: any;
    const history: any;
    const renderCanvas: () => void;
    const clearAllCaches: () => void;
    const getShapeCache: (id: string) => any;
    const getShapeRenderBounds: (id: string) => any;
    const markShapeDirty: (id: string) => void;
    const drawShapeToCanvasContext: (ctx: any, shapeId: string) => void;
    const rasterizeInactiveLayers: () => void;
    const renderMinimap: () => void;
    const renderGuides: (id: string, container: any) => void;
    const pushHistory: () => void;
    const undo: () => void;
    const redo: () => void;
    const handleInputUpdate: (e: any) => void;
    const handleInputUpdate_old: (event: string, detail?: any, rawEvent?: any) => void;
    const updateTransformPivotToCenter: () => void;
    const initDB: () => void;
    const initOffscreenCanvases: () => void;
    const resizeOffscreenCanvases: () => void;
    const saveDrawing: () => Promise<void>;
    const loadGallery: () => void;
    const switchView: (viewId: string) => void;
    const addLayer: () => void;
    const deleteLayer: (id: string) => void;
    const renderLayerList: () => void;
    const startNewDrawing: (type?: string) => void;
    const importImageFile: () => void;
    const getDom: (pat: string) => any;
    const getDoms: (pat: string) => any[];
    const getDomsOf: (root: any, pat: string) => any[];
    const newElm: (tag: string) => any;
    const getMainCanvasSVGVector: () => any;
    const getMainCanvasSVGPoint: () => any;
    const getModifierState: (e: any) => string;
    const isFocusEditable: () => boolean;
    const toggleHelpModal: () => void;
    const handleQuitToGallery: (ctx: any) => void;
    const handleOpenSearch: (ctx: any) => void;
    const handleOpenCommand: (ctx: any) => void;
    const handleSearchNext: (ctx: any) => void;
    const handleSearchPrev: (ctx: any) => void;
    const handleFocusVertexPrev: (ctx: any) => void;
    const handleFocusVertexNext: (ctx: any) => void;
    const performSearch: (val: string) => void;
    const applySearchResult: () => void;
    const closeSearchMode: (commit: boolean) => void;
    const closeCommandMode: (commit: boolean) => void;
    const switchSettingsTab: (tab: string) => void;
    const initWebGLPatternRenderer: () => void;
    const renderPatternWebGL: (positions: any, name: string) => any;
    const generateCoonsPatchMesh: (shape: any) => any;
    const generateStrokeCoonsPatchMesh: (shape: any) => any;
    let currentRenderCoonsCount: number;
    const resetRenderCoonsCount: () => void;
    const addShapeAt: (type: string, x: number, y: number) => void;
    const createWrap: () => void;
    const resolveBezierDependencies: () => void;
}

export {};
