declare global {
    interface Window {
        state: any;
        keyHandlers: any;
        interactionMap: any;
        modeHandlers: any;
        MDMath: any;
        db: any;
        history: any;
        renderCanvas: () => void;
        clearAllCaches: () => void;
        getShapeCache: (id: string) => any;
        getShapeRenderBounds: (id: string) => any;
        markShapeDirty: (id: string) => void;
        drawShapeToCanvasContext: (ctx: any, shapeId: string) => void;
        rasterizeInactiveLayers: () => void;
        renderMinimap: () => void;
        renderGuides: (id: string, container: any) => void;
        pushHistory: () => void;
        undo: () => void;
        redo: () => void;
        handleInputUpdate: (e: any) => void;
        handleInputUpdate_old: (event: string, detail?: any, rawEvent?: any) => void;
        updateTransformPivotToCenter: () => void;
        initDB: () => void;
        initOffscreenCanvases: () => void;
        resizeOffscreenCanvases: () => void;
        saveDrawing: () => Promise<void>;
        loadGallery: () => void;
        switchView: (viewId: string) => void;
        openDrawing: (id: string) => void;
        deleteDrawing: (id: string, e: any) => Promise<void>;
        addLayer: () => void;
        deleteLayer: (id: string) => void;
        renderLayerList: () => void;
        startNewDrawing: (type?: string) => void;
        importImageFile: () => void;
        getDom: (pat: string) => any;
        getDoms: (pat: string) => any[];
        getDomsOf: (root: any, pat: string) => any[];
        getDomOf: (root: any, pat: string) => any;
        addClassDom: (pat: string, className: string) => void;
        removeClassDom: (pat: string, className: string) => void;
        toggleClassDom: (pat: string, className: string) => boolean;
        newElm: (tag: string, attrs?: any) => any;
        getMainCanvasSVGVector: () => any;
        getMainCanvasSVGPoint: () => any;
        getModifierState: (e: any) => string;
        isFocusEditable: () => boolean;
        toggleHelpModal: () => void;
        handleQuitToGallery: (ctx: any) => void;
        handleOpenSearch: (ctx: any) => void;
        handleOpenCommand: (ctx: any) => void;
        handleSearchNext: (ctx: any) => void;
        handleSearchPrev: (ctx: any) => void;
        handleFocusVertexPrev: (ctx: any) => void;
        handleFocusVertexNext: (ctx: any) => void;
        performSearch: (val: string) => void;
        applySearchResult: () => void;
        closeSearchMode: (commit: boolean) => void;
        closeCommandMode: (commit: boolean) => void;
        switchSettingsTab: (tab: string) => void;
        saveImageSettings: () => void;
        initWebGLPatternRenderer: () => void;
        renderPatternWebGL: (positions: any, name: string) => any;
        generateCoonsPatchMesh: (shape: any) => any;
        generateStrokeCoonsPatchMesh: (shape: any) => any;
        currentRenderCoonsCount: number;
        resetRenderCoonsCount: () => void;
        addShapeAt: (type: string, x: number, y: number) => void;
        createWrap: () => void;
        resolveBezierDependencies: () => void;
        handleMove: () => void;
        handleRotate: () => void;
        handleScale: () => void;
        handleConvertRasterToPolyline: (ctx: any) => void;
        handleZoom: () => void;
        handleToggleAnchor: (ctx: any) => void;
        handleEnterAction: (ctx?: any) => void;
        handleTransformStart: (ctx: any) => void;
        handleTransformEnd: (ctx: any) => void;
        handleToggleThicknessEdit: (ctx: any) => void;
        handleToggleOutline: (ctx: any) => void;
        handleToggleFillEnabled: (ctx: any) => void;
        handleTogglePatternEdit: (ctx: any) => void;
        handleUndoAction: (ctx: any) => void;
        handleCopy: (ctx: any) => void;
        handlePaste: (ctx: any) => void;
        handleRedoAction: (ctx: any) => void;
        handleClearVertexFocus: (ctx: any) => void;
        deleteSelectedVertex: (ctx?: any) => void;
        deleteSelectedShapes: (ctx?: any) => void;
        handleDeleteThicknessPoint: (ctx: any) => void;
        handleCreateWrap: (ctx: any) => void;
        handleAddCircleStart: (ctx: any) => void;
        updateSelectionByDragRect: () => void;
        handlePolylineDeform: () => void;
        syncDeformSlidersFromState: () => void;
        handleDDist: (ctx: any) => void;
        generateId: (prefix: string) => string;
        initPatternCorners: (shape: any) => void;
        loadDrawingTexture: (id: string) => any;
        getShapePoint: (shape: any, t: number) => { x: number, y: number };
        handleTSlide: (ctx: any) => void;
        handleTSlideThickness: (ctx: any) => void;
        handleWSlideThickness: (ctx: any) => void;
        handleTMoveThickness: (ctx: any) => void;
        handleTSlidePattern: (ctx: any) => void;
        handleTMovePattern: (ctx: any) => void;
        stateReplacer: (key: string, value: any) => any;
        __debug__: any;
    }

    const state: any;
    const keyHandlers: any;
    const interactionMap: any;
    const modeHandlers: any;
    const MDMath: any;
    let db: any;
    const history: any;
    const renderCanvas: () => void;
    const clearAllCaches: () => void;
    const getShapeCache: (id: string) => any;
    const getShapeRenderBounds: (id: string) => any;
    const markShapeDirty: (id: string) => void;
    const drawShapeToCanvasContext: (ctx: any, shapeId: string) => void;
    const rasterizeInactiveLayers: () => void;
    const renderMinimap: () => void;
    const renderGuides: (id: string, container: any) => void;
    const pushHistory: () => void;
    const undo: () => void;
    const redo: () => void;
    const handleInputUpdate: (e: any) => void;
    const handleInputUpdate_old: (event: string, detail?: any, rawEvent?: any) => void;
    const updateTransformPivotToCenter: () => void;
    const initDB: () => void;
    const initOffscreenCanvases: () => void;
    const resizeOffscreenCanvases: () => void;
    const saveDrawing: () => Promise<void>;
    const loadGallery: () => void;
    const switchView: (viewId: string) => void;
    const openDrawing: (id: string) => void;
    const deleteDrawing: (id: string, e: any) => Promise<void>;
    const addLayer: () => void;
    const deleteLayer: (id: string) => void;
    const renderLayerList: () => void;
    const startNewDrawing: (type?: string) => void;
    const importImageFile: () => void;
    const getDom: (pat: string) => any;
    const getDoms: (pat: string) => any[];
    const getDomsOf: (root: any, pat: string) => any[];
    const getDomOf: (root: any, pat: string) => any;
    const addClassDom: (pat: string, className: string) => void;
    const removeClassDom: (pat: string, className: string) => void;
    const toggleClassDom: (pat: string, className: string) => boolean;
    const newElm: (tag: string, attrs?: any) => any;
    const initializeIdCounter: () => void;
    const getMainCanvasSVGVector: () => any;
    const getMainCanvasSVGPoint: () => any;
    const getModifierState: (e: any) => string;
    const isFocusEditable: () => boolean;
    const toggleHelpModal: () => void;
    const handleQuitToGallery: (ctx: any) => void;
    const handleOpenSearch: (ctx: any) => void;
    const handleOpenCommand: (ctx: any) => void;
    const handleSearchNext: (ctx: any) => void;
    const handleSearchPrev: (ctx: any) => void;
    const handleFocusVertexPrev: (ctx: any) => void;
    const handleFocusVertexNext: (ctx: any) => void;
    const performSearch: (val: string) => void;
    const applySearchResult: () => void;
    const closeSearchMode: (commit: boolean) => void;
    const closeCommandMode: (commit: boolean) => void;
    const switchSettingsTab: (tab: string) => void;
    const saveImageSettings: () => void;
    const initWebGLPatternRenderer: () => void;
    const renderPatternWebGL: (positions: any, name: string) => any;
    const generateCoonsPatchMesh: (shape: any) => any;
    const generateStrokeCoonsPatchMesh: (shape: any) => any;
    let currentRenderCoonsCount: number;
    const resetRenderCoonsCount: () => void;
    const addShapeAt: (type: string, x: number, y: number) => void;
    const createWrap: () => void;
    const resolveBezierDependencies: () => void;
    const handleMove: () => void;
    const handleRotate: () => void;
    const handleScale: () => void;
    const handleConvertRasterToPolyline: (ctx: any) => void;
    const handleZoom: () => void;
    const handleToggleAnchor: (ctx: any) => void;
    const handleEnterAction: (ctx?: any) => void;
    const handleTransformStart: (ctx: any) => void;
    const handleTransformEnd: (ctx: any) => void;
    const handleToggleThicknessEdit: (ctx: any) => void;
    const handleToggleOutline: (ctx: any) => void;
    const handleToggleFillEnabled: (ctx: any) => void;
    const handleTogglePatternEdit: (ctx: any) => void;
    const handleUndoAction: (ctx: any) => void;
    const handleCopy: (ctx: any) => void;
    const handlePaste: (ctx: any) => void;
    const handleRedoAction: (ctx: any) => void;
    const handleClearVertexFocus: (ctx: any) => void;
    const deleteSelectedVertex: (ctx?: any) => void;
    const deleteSelectedShapes: (ctx?: any) => void;
    const handleDeleteThicknessPoint: (ctx: any) => void;
    const handleCreateWrap: (ctx: any) => void;
    const handleAddCircleStart: (ctx: any) => void;
    const updateSelectionByDragRect: () => void;
    const handlePolylineDeform: () => void;
    const syncDeformSlidersFromState: () => void;
    const handleDDist: (ctx: any) => void;
    const generateId: (prefix: string) => string;
    const initPatternCorners: (shape: any) => void;
    const loadDrawingTexture: (id: string) => any;
    const getShapePoint: (shape: any, t: number) => { x: number, y: number };
    const handleTSlide: (ctx: any) => void;
    const handleTSlideThickness: (ctx: any) => void;
    const handleWSlideThickness: (ctx: any) => void;
    const handleTMoveThickness: (ctx: any) => void;
    const handleTSlidePattern: (ctx: any) => void;
    const handleTMovePattern: (ctx: any) => void;
    const stateReplacer: (key: string, value: any) => any;
}

export {};
